-- =============================================================================
-- SMART BANKING SYSTEM - ENTERPRISE ORACLE DATABASE SCHEMA (DDL)
-- =============================================================================
-- This script contains Oracle-compatible SQL to build the core schemas, 
-- constraints, indexes, and automated triggers for the banking application.
-- =============================================================================

-- Clean up existing objects to allow clean re-runs
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE banking_notification CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE banking_fraud_alert CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE banking_transaction CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE banking_account CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE banking_user_profile CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop Sequences if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE seq_transaction_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE seq_fraud_alert_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE seq_notification_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- =============================================================================
-- 1. USER PROFILE TABLE
-- =============================================================================
CREATE TABLE banking_user_profile (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(11) NOT NULL UNIQUE,
    phone_number VARCHAR2(20),
    address VARCHAR2(255),
    national_id VARCHAR2(50) UNIQUE,
    credit_score NUMBER(3) DEFAULT 600,
    monthly_income NUMBER(12, 2) DEFAULT 0.00,
    employment_status VARCHAR2(20) DEFAULT 'Employed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_credit_score CHECK (credit_score BETWEEN 300 AND 850),
    CONSTRAINT chk_employment_status CHECK (employment_status IN ('Employed', 'Self-Employed', 'Unemployed')),
    CONSTRAINT chk_monthly_income CHECK (monthly_income >= 0)
);


-- =============================================================================
-- 2. ACCOUNTS TABLE
-- =============================================================================
CREATE TABLE banking_account (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(11) NOT NULL,
    account_number VARCHAR2(10) NOT NULL UNIQUE,
    account_type VARCHAR2(15) NOT NULL,
    balance NUMBER(15, 2) DEFAULT 0.00 NOT NULL,
    currency VARCHAR2(3) DEFAULT 'USD' NOT NULL,
    status VARCHAR2(15) DEFAULT 'Active' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_balance CHECK (balance >= 0),
    CONSTRAINT chk_account_type CHECK (account_type IN ('Savings', 'Checking', 'Loan')),
    CONSTRAINT chk_account_status CHECK (status IN ('Active', 'Suspended', 'Closed'))
);

-- Index for searching accounts by user ID
CREATE INDEX idx_account_user ON banking_account(user_id);


-- =============================================================================
-- 3. TRANSACTIONS TABLE
-- =============================================================================
CREATE TABLE banking_transaction (
    id NUMBER(19) PRIMARY KEY,
    sender_account_id NUMBER(19),
    receiver_account_id NUMBER(19),
    amount NUMBER(15, 2) NOT NULL,
    transaction_type VARCHAR2(15) NOT NULL,
    status VARCHAR2(15) DEFAULT 'Success' NOT NULL,
    description VARCHAR2(255),
    reference_number VARCHAR2(50) UNIQUE NOT NULL,
    ip_address VARCHAR2(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_tx_amount CHECK (amount > 0),
    CONSTRAINT chk_tx_type CHECK (transaction_type IN ('Deposit', 'Withdrawal', 'Transfer')),
    CONSTRAINT chk_tx_status CHECK (status IN ('Success', 'Failed', 'Flagged')),
    CONSTRAINT fk_tx_sender FOREIGN KEY (sender_account_id) REFERENCES banking_account(id) ON DELETE SET NULL,
    CONSTRAINT fk_tx_receiver FOREIGN KEY (receiver_account_id) REFERENCES banking_account(id) ON DELETE SET NULL
);

-- Sequence for custom Transaction ID generation
CREATE SEQUENCE seq_transaction_id START WITH 100000 INCREMENT BY 1;

-- Index for transaction histories by accounts
CREATE INDEX idx_tx_sender ON banking_transaction(sender_account_id);
CREATE INDEX idx_tx_receiver ON banking_transaction(receiver_account_id);
CREATE INDEX idx_tx_timestamp ON banking_transaction(created_at DESC);


-- =============================================================================
-- 4. FRAUD ALERTS TABLE
-- =============================================================================
CREATE TABLE banking_fraud_alert (
    id NUMBER(19) PRIMARY KEY,
    transaction_id NUMBER(19) NOT NULL,
    reason VARCHAR2(255) NOT NULL,
    severity VARCHAR2(10) DEFAULT 'Low' NOT NULL,
    status VARCHAR2(15) DEFAULT 'Pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_fraud_severity CHECK (severity IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_fraud_status CHECK (status IN ('Pending', 'Resolved', 'False Alarm')),
    CONSTRAINT fk_fraud_tx FOREIGN KEY (transaction_id) REFERENCES banking_transaction(id) ON DELETE CASCADE
);

-- Sequence for Fraud Alert IDs
CREATE SEQUENCE seq_fraud_alert_id START WITH 1 INCREMENT BY 1;

-- Index for searching alerts by transaction or status
CREATE INDEX idx_fraud_status ON banking_fraud_alert(status);


-- =============================================================================
-- 5. NOTIFICATIONS TABLE
-- =============================================================================
CREATE TABLE banking_notification (
    id NUMBER(19) PRIMARY KEY,
    user_id NUMBER(11) NOT NULL,
    title VARCHAR2(100) NOT NULL,
    message CLOB NOT NULL,
    notification_type VARCHAR2(10) NOT NULL,
    recipient_target VARCHAR2(100) NOT NULL,
    status VARCHAR2(10) DEFAULT 'Sent' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notif_type CHECK (notification_type IN ('Email', 'SMS')),
    CONSTRAINT chk_notif_status CHECK (status IN ('Sent', 'Failed'))
);

-- Sequence for Notification IDs
CREATE SEQUENCE seq_notification_id START WITH 1 INCREMENT BY 1;

-- Index for checking notifications history by user ID
CREATE INDEX idx_notification_user ON banking_notification(user_id);

-- =============================================================================
-- 6. DB PROCEDURES AND AUTOMATED TRIGGERS
-- =============================================================================

-- Trigger: Set updated_at timestamp on Profile updates
CREATE OR REPLACE TRIGGER trg_user_profile_updated
BEFORE UPDATE ON banking_user_profile
FOR EACH ROW
BEGIN
    :new.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Trigger: Set updated_at timestamp on Account updates
CREATE OR REPLACE TRIGGER trg_account_updated
BEFORE UPDATE ON banking_account
FOR EACH ROW
BEGIN
    :new.updated_at := CURRENT_TIMESTAMP;
END;
/
